<?php

/**
 * This file is part of milpa/devtools — the generate-verify-inspect developer loop of the Milpa
 * PHP framework.
 *
 * (c) Rodrigo Vicente - TeamX Agency — https://teamx.agency <hola@teamx.agency>
 *
 * @license Apache-2.0
 *
 * @link    https://github.com/getmilpa/devtools
 */

declare(strict_types=1);

namespace Milpa\DevTools\Tests\Tools;

use Milpa\DevTools\Tools\MessageGate;
use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

require_once \dirname(__DIR__, 2) . '/tools/message-gate.php';

/**
 * The controls of the message gate: every refusal it promises, and every text it must let through.
 *
 * A gate with no control is not a gate. Each rule is shown red on a text that breaks it and green on
 * the nearest text that does not — the release bot's own pull request, the merge commit GitHub writes
 * when a branch is updated, the house's everyday words ("session", "generated") used as words.
 *
 * The run is driven with a recorded API so no test needs the network; the last tests start the script
 * as a process against a local server, because the request itself (token, pages, a refusal, a server
 * that fails) is where "could not read" has to end red.
 */
final class ACommitSpeaksForItsAuthorAloneTest extends TestCase
{
    private const SHA = 'a1b2c3d4e5f60718293a4b5c6d7e8f9012345678';

    /** A release as a squash that takes the pull request's body leaves it on main: wrapped at 72 columns, the bot named. */
    private const WRAPPED_RELEASE = <<<'TEXT'
        chore(main): release 1.2.3 (#12)

        :robot: I have created a release *beep* *boop*
        ---


        ##
        [1.2.3](https://github.com/x/y/compare/v1.2.2...v1.2.3)
        (2026-10-07)


        ### Features

        * a grant resumes the call it was given for
        ([#11](https://github.com/x/y/issues/11))
        ([90b5452](https://github.com/x/y/commit/90b545299b2314e495ba9a67f626f92362716b00))

        ---
        This PR was generated with [Release
        Please](https://github.com/googleapis/release-please). See
        [documentation](https://github.com/googleapis/release-please#release-please).

        Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        TEXT;

    /** @var resource|null */
    private $server;

    /** @var list<string> */
    private array $temporary = [];

    protected function tearDown(): void
    {
        if (\is_resource($this->server)) {
            proc_terminate($this->server);
            proc_close($this->server);
        }
        $this->server = null;

        foreach ($this->temporary as $file) {
            @unlink($file);
        }
        $this->temporary = [];
    }

    // ── the rules ────────────────────────────────────────────────────────────────────────────────

    /** @return iterable<string, array{string}> */
    public static function textsThatPass(): iterable
    {
        yield 'a plain commit' => ["fix: the reader keeps its place\n\nIt lost the offset when the page turned."];
        yield 'the squashed release, where GitHub names the bot' => ["chore(main): release 1.2.3 (#12)\n\nCo-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"];
        yield 'a maintainer named by GitHub on a squash' => ["chore(main): release 1.2.3 (#12)\n\nCo-authored-by: Rod Vince <rodrigo@teamx.agency>"];
        yield 'an admitted address in another case' => ['Co-Authored-By: Someone <Rodrigo@TeamX.Agency>'];
        yield 'the dependency bot named by GitHub on a squash' => ["chore(deps): update x to v2 (#9)\n\nCo-authored-by: renovate[bot] <29139614+renovate[bot]@users.noreply.github.com>"];
        yield 'the release bot signs its pull request' => ["---\nThis PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please)."];
        yield 'the dependency bot signs its pull request' => ['This PR was generated by [Mend Renovate](https://mend.io/renovate/). View the [repository job log](https://developer.mend.io/github/x/y).'];
        yield 'the merge commit GitHub writes when a branch is updated' => ["Merge branch 'main' into feature/the-reader"];
        yield 'the words used as words, mid-line' => ['The catalogue is generated by `coa docs:build`, and the map is generated with the same pass.'];
        yield 'a session as the house means it' => ["The session ledger keeps its order.\n\n`agent --session` resumes it; see http://localhost:8080/workspace?session=4f9d2c1ab37e"];
        yield 'a co-author spoken of, not named' => ['The gate refuses a co-author trailer; Co-authored-by is the key GitHub reads.'];
        yield 'a sentence a wrap broke before the words' => ["The map and the catalogue of every operation the house declares are\ngenerated by the build, and the index is\ngenerated with the same pass."];
        yield 'the squashed release as GitHub wraps it onto main' => [self::WRAPPED_RELEASE];
        yield 'the empty text' => [''];
    }

    #[DataProvider('textsThatPass')]
    public function testAnHonestTextPasses(string $text): void
    {
        self::assertSame([], MessageGate::judge($text));
    }

    /** @return iterable<string, array{string, string, int}> */
    public static function textsThatAreRefused(): iterable
    {
        yield 'a co-author the house does not list' => ["fix: x\n\nCo-authored-by: Some Tool <noreply@tool.example>", MessageGate::COAUTHOR, 3];
        yield 'the same trailer in the other spelling' => ["fix: x\n\nCo-Authored-By: Some Tool <noreply@tool.example>", MessageGate::COAUTHOR, 3];
        yield 'the trailer quoted in a list' => ["Notes\n- `Co-authored-by: Some Tool <noreply@tool.example>`", MessageGate::COAUTHOR, 2];
        yield 'a trailer with no address' => ['Co-authored-by: Some Tool', MessageGate::COAUTHOR, 1];
        yield 'a listed co-author beside an unlisted one' => ['Co-authored-by: Rod <rodrigo@teamx.agency> Co-authored-by: Some Tool <noreply@tool.example>', MessageGate::COAUTHOR, 1];
        yield 'a listed name with an unlisted address' => ['Co-authored-by: github-actions[bot] <noreply@tool.example>', MessageGate::COAUTHOR, 1];
        yield 'a generator signs the pull request' => ["Summary\n\n\u{1F916} Generated with [Some Tool](https://tool.example/code)", MessageGate::GENERATOR, 3];
        yield 'the signature without a link' => ['Generated by Some Tool', MessageGate::GENERATOR, 1];
        yield 'the signature dressed in markup' => ['<sub>_Generated with Some Tool_</sub>', MessageGate::GENERATOR, 1];
        yield 'the signature quoted' => ['> Generated-by: Some Tool', MessageGate::GENERATOR, 1];
        yield 'the signature in capitals' => ['GENERATED BY SOME TOOL', MessageGate::GENERATOR, 1];
        yield 'the signature in small letters, linking the generator' => ['generated with [Some Tool](https://tool.example)', MessageGate::GENERATOR, 1];
        yield 'the linked signature mid-line, in another case' => ['This PR was Generated With [Some Tool](https://tool.example).', MessageGate::GENERATOR, 1];
        yield 'the signature mid-line, linking the generator' => ['This PR was generated with [Some Tool](https://tool.example).', MessageGate::GENERATOR, 1];
        yield 'a link that only begins like an admitted generator' => ['This PR was generated with [Release Please](https://github.com/googleapis/release-please-but-not).', MessageGate::GENERATOR, 1];
        yield 'the signature with a no-break space' => ["Generated\u{00A0}with [Some Tool](https://tool.example)", MessageGate::GENERATOR, 1];
        yield 'the signature after a broken byte' => ["\xFF\xFE Generated with Some Tool", MessageGate::GENERATOR, 1];
        yield 'a session trailer' => ["fix: x\r\n\r\nTool-Session: 01HZX4", MessageGate::SESSION, 3];
        yield 'a session id trailer' => ['X-Tool-Session-Id: 01HZX4', MessageGate::SESSION, 1];
        yield 'a link to a session page' => ['Worked out in https://tool.example/code/session_01Y1KzQQVduS83c6ZArZZ96s today.', MessageGate::SESSION, 1];
    }

    #[DataProvider('textsThatAreRefused')]
    public function testARefusedTextNamesItsLineAndItsRule(string $text, string $rule, int $line): void
    {
        self::assertSame([['line' => $line, 'rule' => $rule]], MessageGate::judge($text));
    }

    public function testOneLineCanBreakTwoRules(): void
    {
        $found = MessageGate::judge("fix: x\n\nTool-Session: https://tool.example/code/session_01Y1KzQQVduS83c6ZArZZ96s\nCo-authored-by: Some Tool <noreply@tool.example>");

        self::assertSame([
            ['line' => 3, 'rule' => MessageGate::SESSION],
            ['line' => 4, 'rule' => MessageGate::COAUTHOR],
        ], $found);
    }

    /** A title becomes the first line of the squashed commit; what follows "fix: " is read as that line. */
    public function testATitleIsJudgedAfterItsConventionalPrefix(): void
    {
        self::assertSame([['line' => 1, 'rule' => MessageGate::GENERATOR]], MessageGate::judge('fix(docs)!: Generated by Some Tool', true));
        self::assertSame([], MessageGate::judge('fix: Generated by Some Tool'), 'read as a commit line, the prefix opens it');
        self::assertSame([], MessageGate::judge('fix: the docs are generated by the build', true));
        self::assertSame([], MessageGate::judge('chore(main): release 1.2.3', true));
    }

    // ── a pull request ───────────────────────────────────────────────────────────────────────────

    public function testACleanPullRequestPasses(): void
    {
        [$code, $said] = $this->gate($this->pullRequestEvent(7), self::api(7, 'fix: the reader keeps its place', 'It lost the offset.', ['fix: the reader keeps its place', 'test: the page turns']));

        self::assertSame(0, $code, $said);
        self::assertStringContainsString('the title and the body and 2 commits read', $said);
    }

    public function testACommitWithACoauthorTrailerIsRefusedAndNeverQuoted(): void
    {
        [$code, $said] = $this->gate($this->pullRequestEvent(7), self::api(7, 'fix: x', 'A body.', ['fix: x', "fix: y\n\nCo-authored-by: Some Tool <noreply@tool.example>"]));

        self::assertSame(1, $code);
        self::assertStringContainsString('::error title=Message gate::commit ' . substr(self::sha(1), 0, 9) . ', line 3: ' . MessageGate::COAUTHOR, $said);
        self::assertStringContainsString('1 line refused', $said);
        self::assertStringNotContainsString('tool.example', $said, 'the log of a gate is as public as the commit it judged');
        self::assertStringNotContainsString('Some Tool', $said);
    }

    public function testABodyWithAGeneratorSignatureIsRefused(): void
    {
        [$code, $said] = $this->gate($this->pullRequestEvent(7), self::api(7, 'fix: x', "What changed.\n\nGenerated with [Some Tool](https://tool.example)", ['fix: x']));

        self::assertSame(1, $code);
        self::assertStringContainsString('the pull request body, line 3: ' . MessageGate::GENERATOR, $said);
    }

    public function testATitleIsReadToo(): void
    {
        [$code, $said] = $this->gate($this->pullRequestEvent(7), self::api(7, 'fix: x Co-authored-by: Some Tool <noreply@tool.example>', '', ['fix: x']));

        self::assertSame(1, $code);
        self::assertStringContainsString('the pull request title, line 1: ' . MessageGate::COAUTHOR, $said);
    }

    /**
     * The body is asked of the API, never taken from the event that started the run: the event of a
     * re-run still carries the body the pull request had when it was opened.
     */
    public function testTheBodyIsReadAsItIsNowNotAsTheEventRemembersIt(): void
    {
        $stale = "Old body.\n\nGenerated with [Some Tool](https://tool.example)";

        [$cleaned] = $this->gate($this->pullRequestEvent(7, $stale), self::api(7, 'fix: x', 'Old body.', ['fix: x']));
        [$dirtied] = $this->gate($this->pullRequestEvent(7, 'Old body.'), self::api(7, 'fix: x', $stale, ['fix: x']));

        self::assertSame(0, $cleaned, 'a re-run after the body was cleaned passes');
        self::assertSame(1, $dirtied, 'a re-run after the body was dirtied does not');
    }

    public function testTheReleaseBotsPullRequestPasses(): void
    {
        $body = ":robot: I have created a release *beep* *boop*\n---\n\n\n## [1.2.3](https://github.com/x/y/compare/v1.2.2...v1.2.3) (2026-10-06)\n\n\n### Bug Fixes\n\n"
            . "* the reader keeps its place ([#11](https://github.com/x/y/issues/11)) ([a1b2c3d](https://github.com/x/y/commit/a1b2c3d))\n\n---\n"
            . 'This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).';

        [$code, $said] = $this->gate($this->pullRequestEvent(12), self::api(12, 'chore(main): release 1.2.3', $body, ['chore(main): release 1.2.3']));

        self::assertSame(0, $code, $said);
    }

    public function testABranchUpdatedFromItsBasePasses(): void
    {
        [$code, $said] = $this->gate($this->pullRequestEvent(7), self::api(7, 'fix: x', 'A body.', ['fix: x', "Merge branch 'main' into feature/x"]));

        self::assertSame(0, $code, $said);
    }

    public function testEveryPageOfCommitsIsRead(): void
    {
        $messages = array_fill(0, 120, 'fix: one more step');
        $messages[117] = "fix: one more step\n\nCo-authored-by: Some Tool <noreply@tool.example>";
        $asked = [];

        [$code, $said] = $this->gate($this->pullRequestEvent(7), self::api(7, 'fix: x', '', $messages), $asked);

        self::assertSame(1, $code);
        self::assertStringContainsString('commit ' . substr(self::sha(117), 0, 9) . ', line 3', $said);
        self::assertContains('/repos/x/y/pulls/7/commits?per_page=100&page=2', $asked);
    }

    public function testAPullRequestWithMoreCommitsThanTheApiListsIsNotJudged(): void
    {
        $api = static fn (string $path): array => ['title' => 'fix: x', 'body' => '', 'commits' => 251];

        [$code, $said] = $this->gate($this->pullRequestEvent(7), $api);

        self::assertSame(1, $code);
        self::assertStringContainsString('NOT JUDGED', $said);
        self::assertStringContainsString('251 commits', $said);
    }

    public function testFewerCommitsThanAnnouncedIsNotJudged(): void
    {
        $api = self::api(7, 'fix: x', '', ['fix: x']);
        $short = static fn (string $path): array => str_contains($path, '/commits') ? $api($path) : ['commits' => 3] + $api($path);

        [$code, $said] = $this->gate($this->pullRequestEvent(7), $short);

        self::assertSame(1, $code);
        self::assertStringContainsString('3 commits were announced and only 1 could be read', $said);
    }

    public function testAnApiThatDoesNotAnswerIsNotAPass(): void
    {
        $api = static fn (string $path): array => throw new \RuntimeException('the API answered 403 to ' . $path . '.');

        [$code, $said] = $this->gate($this->pullRequestEvent(7), $api);

        self::assertSame(1, $code);
        self::assertStringContainsString('::error title=Message gate::not judged', $said);
        self::assertStringContainsString('Not being able to read is not passing.', $said);
    }

    public function testAnAnswerWithoutATitleIsNotAPullRequest(): void
    {
        [$code, $said] = $this->gate($this->pullRequestEvent(7), static fn (string $path): array => ['message' => 'Not Found']);

        self::assertSame(1, $code);
        self::assertStringContainsString('pull request #7 could not be read', $said);
    }

    // ── a push ───────────────────────────────────────────────────────────────────────────────────

    public function testAPushIsJudgedByTheCommitsItAdded(): void
    {
        $asked = [];
        $clean = self::compare(['fix: x (#7)', "chore(main): release 1.2.3 (#12)\n\nCo-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>"]);
        $dirty = self::compare(['fix: x (#7)', "fix: y (#8)\n\nCo-authored-by: Some Tool <noreply@tool.example>"]);

        [$passes, $said] = $this->gate($this->pushEvent(self::sha(8), self::sha(9)), $clean, $asked);
        [$fails, $refusal] = $this->gate($this->pushEvent(self::sha(8), self::sha(9)), $dirty);

        self::assertSame(0, $passes, $said);
        self::assertStringContainsString('2 commits read', $said);
        self::assertSame(['/repos/x/y/compare/' . self::sha(8) . '...' . self::sha(9) . '?per_page=100&page=1'], $asked);
        self::assertSame(1, $fails);
        self::assertStringContainsString('commit ' . substr(self::sha(1), 0, 9) . ', line 3: ' . MessageGate::COAUTHOR, $refusal);
    }

    public function testAPushOfManyCommitsReadsThemAll(): void
    {
        $messages = array_fill(0, 130, 'fix: one more step');
        $messages[129] = "fix: the last one\n\nTool-Session: 01HZX4";

        [$code, $said] = $this->gate($this->pushEvent(self::sha(8), self::sha(9)), self::compare($messages));

        self::assertSame(1, $code);
        self::assertStringContainsString('commit ' . substr(self::sha(129), 0, 9) . ', line 3: ' . MessageGate::SESSION, $said);
    }

    public function testANewBranchIsJudgedByItsTip(): void
    {
        $asked = [];
        $api = static fn (string $path): array => ['sha' => self::SHA, 'commit' => ['message' => "fix: x\n\nGenerated by Some Tool"]];

        [$code, $said] = $this->gate($this->pushEvent(str_repeat('0', 40), self::SHA), $api, $asked);

        self::assertSame(1, $code);
        self::assertSame(['/repos/x/y/commits/' . self::SHA], $asked);
        self::assertStringContainsString('commit ' . substr(self::SHA, 0, 9) . ', line 3: ' . MessageGate::GENERATOR, $said);
    }

    public function testAPushThatCannotBeComparedIsNotJudged(): void
    {
        [$code, $said] = $this->gate($this->pushEvent(self::sha(8), self::sha(9)), static fn (string $path): array => ['message' => 'Not Found']);
        [$nameless] = $this->gate($this->pushEvent(self::sha(8), ''), static fn (string $path): array => []);
        [$headless] = $this->gate($this->pushEvent(self::sha(8), self::sha(9)), static fn (string $path): array => ['total_commits' => 1, 'commits' => [['sha' => self::SHA]]]);

        self::assertSame(1, $code);
        self::assertStringContainsString('could not be compared', $said);
        self::assertSame(1, $nameless);
        self::assertSame(1, $headless);
    }

    // ── everything else ──────────────────────────────────────────────────────────────────────────

    public function testAnEventThatBringsNoTextHasNothingToJudge(): void
    {
        $never = static fn (string $path): array => throw new \LogicException('nothing should be asked');

        [$code, $said] = $this->gate(['GITHUB_EVENT_NAME' => 'workflow_dispatch', 'GITHUB_REPOSITORY' => 'x/y', 'GITHUB_EVENT_PATH' => $this->payload([])], $never);

        self::assertSame(0, $code);
        self::assertStringContainsString('nothing to judge', $said);
    }

    public function testOutsideAnEventItSaysSoInsteadOfPassing(): void
    {
        $never = static fn (string $path): array => throw new \LogicException('nothing should be asked');

        [$nowhere, $said] = $this->gate([], $never);
        [$unreadable] = $this->gate(['GITHUB_EVENT_NAME' => 'pull_request', 'GITHUB_REPOSITORY' => 'x/y', 'GITHUB_EVENT_PATH' => '/nonexistent/event.json'], $never);
        [$numberless] = $this->gate(['GITHUB_EVENT_NAME' => 'pull_request', 'GITHUB_REPOSITORY' => 'x/y', 'GITHUB_EVENT_PATH' => $this->payload(['action' => 'opened'])], $never);

        self::assertSame(1, $nowhere);
        self::assertStringContainsString('--pr or --stdin', $said);
        self::assertSame(1, $unreadable);
        self::assertSame(1, $numberless);
    }

    public function testAnyPullRequestCanBeJudgedByName(): void
    {
        $asked = [];

        [$code] = $this->gate([], self::api(41, 'fix: x', '', ["fix: x\n\nCo-authored-by: Some Tool <noreply@tool.example>"], 'getmilpa/devtools'), $asked, ['--pr', 'getmilpa/devtools#41']);
        [$malformed, $said] = $this->gate([], self::api(41, 'fix: x', '', ['fix: x']), $asked, ['--pr', 'forty-one']);

        self::assertSame(1, $code);
        self::assertContains('/repos/getmilpa/devtools/pulls/41', $asked);
        self::assertSame(1, $malformed);
        self::assertStringContainsString('--pr takes owner/repo#number', $said);
    }

    public function testOneTextCanBeJudgedFromStandardInput(): void
    {
        $never = static fn (string $path): array => throw new \LogicException('nothing should be asked');
        $asked = [];

        [$clean, $said] = $this->gate([], $never, $asked, ['--stdin'], "fix: x\n\nA body.");
        [$dirty] = $this->gate([], $never, $asked, ['--stdin'], "fix: x\n\nCo-authored-by: Some Tool <noreply@tool.example>");
        [$title] = $this->gate([], $never, $asked, ['--stdin', '--title'], 'fix: Generated with Some Tool');

        self::assertSame(0, $clean);
        self::assertStringContainsString('one text read', $said);
        self::assertSame(1, $dirty);
        self::assertSame(1, $title);
    }

    // ── the script, as CI starts it ──────────────────────────────────────────────────────────────

    public function testTheScriptReadsAPullRequestOverHttpWithItsToken(): void
    {
        $base = $this->serve([
            '/repos/x/y/pulls/7' => [200, ['title' => 'fix: x', 'body' => 'A body.', 'commits' => 1]],
            '/repos/x/y/pulls/7/commits?per_page=100&page=1' => [200, [['sha' => self::SHA, 'commit' => ['message' => 'fix: x']]]],
        ]);

        [$code, $said] = $this->script($this->pullRequestEvent(7) + ['GITHUB_API_URL' => $base, 'GITHUB_TOKEN' => 't0ken']);

        self::assertSame(0, $code, $said);
        self::assertStringContainsString('the title and the body and 1 commit read', $said);
        self::assertSame(['Bearer t0ken /repos/x/y/pulls/7', 'Bearer t0ken /repos/x/y/pulls/7/commits?per_page=100&page=1'], $this->requests());
    }

    public function testTheScriptEndsRedOnARefusedBody(): void
    {
        $base = $this->serve([
            '/repos/x/y/pulls/7' => [200, ['title' => 'fix: x', 'body' => 'Generated by Some Tool', 'commits' => 1]],
            '/repos/x/y/pulls/7/commits?per_page=100&page=1' => [200, [['sha' => self::SHA, 'commit' => ['message' => 'fix: x']]]],
        ]);

        [$code, $said] = $this->script($this->pullRequestEvent(7) + ['GITHUB_API_URL' => $base, 'GITHUB_TOKEN' => 't0ken']);

        self::assertSame(1, $code);
        self::assertStringContainsString('the pull request body, line 1: ' . MessageGate::GENERATOR, $said);
    }

    public function testARefusalFromTheApiEndsRedWithoutAskingAgain(): void
    {
        $base = $this->serve(['/repos/x/y/pulls/7' => [403, ['message' => 'Resource not accessible by integration']]]);

        [$code, $said] = $this->script($this->pullRequestEvent(7) + ['GITHUB_API_URL' => $base, 'GITHUB_TOKEN' => 't0ken']);

        self::assertSame(1, $code);
        self::assertStringContainsString('NOT JUDGED — the API answered 403 to /repos/x/y/pulls/7.', $said);
        self::assertCount(1, $this->requests());
    }

    public function testAFailingServerIsAskedAgainAndThenEndsRed(): void
    {
        $base = $this->serve(['/repos/x/y/pulls/7' => [502, ['message' => 'Bad Gateway']]]);

        [$code, $said] = $this->script($this->pullRequestEvent(7) + ['GITHUB_API_URL' => $base, 'GITHUB_TOKEN' => 't0ken']);

        self::assertSame(1, $code);
        self::assertStringContainsString('the API answered 502', $said);
        self::assertCount(3, $this->requests());
    }

    public function testTheScriptJudgesStandardInput(): void
    {
        [$clean] = $this->script([], ['--stdin'], "fix: x\n");
        [$dirty, $said] = $this->script([], ['--stdin'], "fix: x\n\nCo-authored-by: Some Tool <noreply@tool.example>\n");

        self::assertSame(0, $clean);
        self::assertSame(1, $dirty);
        self::assertStringContainsString('the text, line 3: ' . MessageGate::COAUTHOR, $said);
    }

    // ── what the tests stand on ──────────────────────────────────────────────────────────────────

    /**
     * Runs the gate in this process against a recorded API.
     *
     * @param array<string, string>          $env
     * @param callable(string): array<mixed> $api
     * @param list<string>                   $asked     every path that was asked, in order
     * @param list<string>                   $arguments
     *
     * @return array{int, string} the exit code and everything that was said
     */
    private function gate(array $env, callable $api, array &$asked = [], array $arguments = [], string $stdin = ''): array
    {
        $said = [];
        $fetch = static function (string $path) use ($api, &$asked): array {
            $asked[] = $path;

            return $api($path);
        };

        $code = MessageGate::run(['message-gate.php', ...$arguments], $env, $fetch, static function (string $line) use (&$said): void {
            $said[] = $line;
        }, $stdin);

        return [$code, implode("\n", $said)];
    }

    /**
     * A recorded API holding one pull request: its title, its body, and one commit per message.
     *
     * @param list<string> $messages
     *
     * @return callable(string): array<mixed>
     */
    private static function api(int $number, string $title, string $body, array $messages, string $repository = 'x/y'): callable
    {
        return static function (string $path) use ($number, $title, $body, $messages, $repository): array {
            if ($path === "/repos/{$repository}/pulls/{$number}") {
                return ['title' => $title, 'body' => $body === '' ? null : $body, 'commits' => \count($messages)];
            }

            if (preg_match("~^/repos/{$repository}/pulls/{$number}/commits\\?per_page=100&page=(\\d+)$~", $path, $m) === 1) {
                return self::page($messages, (int) $m[1]);
            }

            throw new \RuntimeException('the API answered 404 to ' . $path . '.');
        };
    }

    /**
     * A recorded API holding one comparison between two commits.
     *
     * @param list<string> $messages
     *
     * @return callable(string): array<mixed>
     */
    private static function compare(array $messages): callable
    {
        return static function (string $path) use ($messages): array {
            if (preg_match('~^/repos/x/y/compare/[0-9a-f]{40}\.\.\.[0-9a-f]{40}\?per_page=100&page=(\d+)$~', $path, $m) !== 1) {
                throw new \RuntimeException('the API answered 404 to ' . $path . '.');
            }

            return ['total_commits' => \count($messages), 'commits' => self::page($messages, (int) $m[1])];
        };
    }

    /**
     * @param list<string> $messages
     *
     * @return list<array{sha: string, commit: array{message: string}}>
     */
    private static function page(array $messages, int $page): array
    {
        $commits = [];
        foreach (\array_slice($messages, ($page - 1) * 100, 100, true) as $index => $message) {
            $commits[] = ['sha' => self::sha($index), 'commit' => ['message' => $message]];
        }

        return $commits;
    }

    private static function sha(int $index): string
    {
        return sha1('commit ' . $index);
    }

    /**
     * @return array<string, string>
     */
    private function pullRequestEvent(int $number, string $rememberedBody = 'A body.'): array
    {
        return [
            'GITHUB_EVENT_NAME' => 'pull_request',
            'GITHUB_REPOSITORY' => 'x/y',
            'GITHUB_EVENT_PATH' => $this->payload(['action' => 'opened', 'number' => $number, 'pull_request' => ['number' => $number, 'title' => 'fix: x', 'body' => $rememberedBody]]),
        ];
    }

    /**
     * @return array<string, string>
     */
    private function pushEvent(string $before, string $after): array
    {
        return [
            'GITHUB_EVENT_NAME' => 'push',
            'GITHUB_REPOSITORY' => 'x/y',
            'GITHUB_EVENT_PATH' => $this->payload(['ref' => 'refs/heads/main', 'before' => $before, 'after' => $after]),
        ];
    }

    /**
     * @param array<string, mixed> $event
     */
    private function payload(array $event): string
    {
        $file = $this->temporary[] = (string) tempnam(sys_get_temp_dir(), 'message-gate-event-');
        file_put_contents($file, json_encode($event, \JSON_THROW_ON_ERROR));

        return $file;
    }

    /**
     * Starts a local server that answers the given paths, and returns its address.
     *
     * @param array<string, array{int, array<mixed>}> $routes path (with its query) to status and answer
     */
    private function serve(array $routes): string
    {
        $routesFile = $this->temporary[] = (string) tempnam(sys_get_temp_dir(), 'message-gate-routes-');
        $logFile = $this->temporary[] = $routesFile . '.log';
        file_put_contents($routesFile, json_encode($routes, \JSON_THROW_ON_ERROR));
        file_put_contents($logFile, '');

        $probe = stream_socket_server('tcp://127.0.0.1:0');
        self::assertIsResource($probe);
        $port = (int) substr((string) strrchr((string) stream_socket_get_name($probe, false), ':'), 1);
        fclose($probe);

        $server = proc_open(
            [\PHP_BINARY, '-S', "127.0.0.1:{$port}", \dirname(__DIR__) . '/Fixtures/message-gate-api.php'],
            [['file', '/dev/null', 'r'], ['file', '/dev/null', 'w'], ['file', '/dev/null', 'w']],
            $pipes,
            null,
            ['MESSAGE_GATE_ROUTES' => $routesFile, 'MESSAGE_GATE_LOG' => $logFile],
        );
        self::assertIsResource($server);
        $this->server = $server;

        for ($waited = 0; $waited < 100; ++$waited) {
            $connection = @fsockopen('127.0.0.1', $port, $errno, $error, 0.1);
            if (\is_resource($connection)) {
                fclose($connection);

                return "http://127.0.0.1:{$port}";
            }
            usleep(50_000);
        }

        self::fail('the local server did not start');
    }

    /**
     * Every request the local server received: "<authorization> <path>".
     *
     * @return list<string>
     */
    private function requests(): array
    {
        foreach ($this->temporary as $file) {
            if (str_ends_with($file, '.log')) {
                return array_values(array_filter(explode("\n", (string) file_get_contents($file))));
            }
        }

        return [];
    }

    /**
     * Starts the script as CI does and returns its exit code and output.
     *
     * @param array<string, string> $env
     * @param list<string>          $arguments
     *
     * @return array{int, string}
     */
    private function script(array $env, array $arguments = [], string $stdin = ''): array
    {
        $process = proc_open(
            [\PHP_BINARY, \dirname(__DIR__, 2) . '/tools/message-gate.php', ...$arguments],
            [['pipe', 'r'], ['pipe', 'w'], ['pipe', 'w']],
            $pipes,
            null,
            $env,
        );
        self::assertIsResource($process);

        fwrite($pipes[0], $stdin);
        fclose($pipes[0]);
        $said = stream_get_contents($pipes[1]) . stream_get_contents($pipes[2]);
        fclose($pipes[1]);
        fclose($pipes[2]);

        return [proc_close($process), (string) $said];
    }
}
