<?php

/**
 * This file is part of milpa/devtools — the generate-verify-inspect developer loop of the Milpa
 * PHP framework.
 *
 * (c) Rodrigo Vicente - TeamX Agency — https://teamx.agency <hola@teamx.agency>
 *
 * @license Apache-2.0
 *
 * @link    https://github.com/getmilpa/devtools
 */

declare(strict_types=1);

namespace Milpa\DevTools\Tools;

/**
 * Message gate: a commit speaks for its author alone.
 *
 * The house rule, in three lines. A commit message — and a pull request's title and body, which
 * become the commit when the pull request is squashed — carries:
 *
 *   1. no co-author trailer, except for the identities listed in ADMITTED_COAUTHORS;
 *   2. no generator signature: a line that opens with "Generated with" or "Generated by", or
 *      those words followed by a link, except for the generators listed in ADMITTED_GENERATORS;
 *   3. no session reference: a trailer whose key ends in "Session", or a link to a session page.
 *
 * It exists because the rule lived in prose, and prose holds while somebody remembers it. Nothing
 * in CI read a commit message or a pull request body, so whatever a branch carried reached main
 * with the merge.
 *
 * WHAT IT READS, AND WHEN. On a pull request: the title and body AS THEY ARE NOW (asked of the
 * API, never taken from the event that started the run — a re-run after an edit must see the
 * edit) and every commit of the pull request. On a push: the commits that push added. On any
 * other event there is no new text, and it says so.
 *
 * NOT BEING ABLE TO READ IS NOT PASSING. A failed request, or a pull request with more commits
 * than the API lists, ends red with the reason.
 *
 * IT NEVER REPEATS WHAT IT REFUSES. A finding names the text, the line and the rule, not the line's
 * content: the log of a gate is as public as the commit it judged.
 *
 * Usage: php tools/message-gate.php                      inside GitHub Actions (reads the event)
 *        php tools/message-gate.php --pr owner/repo#12   any pull request, from anywhere
 *        php tools/message-gate.php --stdin [--title]    one text on standard input
 *
 * The token is read from GITHUB_TOKEN (or GH_TOKEN); reading is all it needs.
 */
final class MessageGate
{
    /**
     * Who may be named as a co-author: the house's maintainers, and the bots GitHub names on the
     * squashed commit of every pull request they open. Addresses, compared without case.
     */
    public const ADMITTED_COAUTHORS = [
        'rodrigo@teamx.agency',
        '41898282+github-actions[bot]@users.noreply.github.com',
        '29139614+renovate[bot]@users.noreply.github.com',
    ];

    /** Whose generator signature may stay: these bots sign the pull requests they open. */
    public const ADMITTED_GENERATORS = [
        'github.com/googleapis/release-please',
        'mend.io/renovate',
    ];

    public const COAUTHOR = 'a co-author trailer for an identity this house does not list';
    public const GENERATOR = 'a generator signature';
    public const SESSION = 'a session reference';

    /** The API lists at most this many commits for one pull request. */
    private const LISTED_COMMITS = 250;

    private const PAGE = 100;

    /**
     * Judges one text and returns what it carries that the rule refuses.
     *
     * @param string $text    a commit message, or a pull request's title or body
     * @param bool   $isTitle a title is judged after its conventional prefix ("fix(scope): ")
     *
     * @return list<array{line: int, rule: string}> one entry per refused line and rule, in order
     */
    public static function judge(string $text, bool $isTitle = false): array
    {
        $findings = [];
        $lines = preg_split('/\r\n|\r|\n/', $text) ?: [];

        foreach ($lines as $index => $line) {
            $number = $index + 1;
            $line = str_replace("\u{00A0}", ' ', $line);

            foreach (self::coauthors($line) as $address) {
                if (!\in_array(strtolower($address), self::ADMITTED_COAUTHORS, true)) {
                    $findings[] = ['line' => $number, 'rule' => self::COAUTHOR];

                    break;
                }
            }

            if (self::signsAGenerator($isTitle ? self::withoutPrefix($line) : $line)) {
                $findings[] = ['line' => $number, 'rule' => self::GENERATOR];
            }

            if (self::refersToASession($line)) {
                $findings[] = ['line' => $number, 'rule' => self::SESSION];
            }
        }

        return $findings;
    }

    /**
     * Runs the gate and returns its exit code; everything it says goes through $say.
     *
     * @param list<string>                   $argv  the command line, script name first
     * @param array<string, string>          $env   the environment it may read
     * @param callable(string): array<mixed> $fetch answers an API path with the decoded JSON, or throws
     * @param callable(string): void         $say   prints one line
     * @param string                         $stdin the text to judge under --stdin
     */
    public static function run(array $argv, array $env, callable $fetch, callable $say, string $stdin = ''): int
    {
        $args = \array_slice($argv, 1);

        try {
            if (\in_array('--stdin', $args, true)) {
                $texts = [['where' => 'the text', 'text' => $stdin, 'title' => \in_array('--title', $args, true)]];
            } elseif (($at = array_search('--pr', $args, true)) !== false) {
                [$repository, $number] = self::named((string) ($args[$at + 1] ?? ''));
                $texts = self::pullRequest($repository, $number, $fetch);
            } else {
                $texts = self::event($env, $fetch);
            }
        } catch (\RuntimeException $e) {
            $say('::error title=Message gate::not judged — ' . $e->getMessage());
            $say('Message gate: NOT JUDGED — ' . $e->getMessage() . ' Not being able to read is not passing.');

            return 1;
        }

        if ($texts === null) {
            $say('Message gate: this event brings no new commit and no pull request text; nothing to judge.');

            return 0;
        }

        $found = 0;
        foreach ($texts as $text) {
            foreach (self::judge($text['text'], $text['title'] ?? false) as $finding) {
                ++$found;
                $say(sprintf('::error title=Message gate::%s, line %d: %s', $text['where'], $finding['line'], $finding['rule']));
            }
        }

        $read = self::tally($texts);

        if ($found === 0) {
            $say("Message gate: {$read} read; each speaks for its author alone.");

            return 0;
        }

        $say('');
        $say("Message gate: {$found} " . ($found === 1 ? 'line' : 'lines') . " refused in {$read}.");
        $say('The rule of this house: a commit speaks for its author alone. Its message, and the title and');
        $say('body of its pull request, carry no co-author trailer for an identity the house does not list,');
        $say('no generator signature and no session reference.');
        $say('To pass: reword the commit (amend or rebase, then push the branch again) or edit the pull');
        $say('request; the gate reads both again on its next run.');

        return 1;
    }

    /**
     * The texts the current GitHub Actions event brings, or null when it brings none.
     *
     * @param array<string, string>          $env
     * @param callable(string): array<mixed> $fetch
     *
     * @return list<array{where: string, text: string, title?: bool}>|null
     */
    private static function event(array $env, callable $fetch): ?array
    {
        $name = $env['GITHUB_EVENT_NAME'] ?? '';
        $repository = $env['GITHUB_REPOSITORY'] ?? '';
        $path = $env['GITHUB_EVENT_PATH'] ?? '';

        if ($name === '' || $repository === '') {
            throw new \RuntimeException('no GitHub Actions event here (GITHUB_EVENT_NAME, GITHUB_REPOSITORY); use --pr or --stdin outside one.');
        }

        $event = is_file($path) ? json_decode((string) file_get_contents($path), true) : null;
        if (!\is_array($event)) {
            throw new \RuntimeException("the event's payload could not be read.");
        }

        if (\in_array($name, ['pull_request', 'pull_request_target'], true)) {
            $number = $event['pull_request']['number'] ?? $event['number'] ?? null;
            if (!\is_int($number)) {
                throw new \RuntimeException('the event names no pull request.');
            }

            return self::pullRequest($repository, $number, $fetch);
        }

        if ($name === 'push') {
            return self::push($repository, (string) ($event['before'] ?? ''), (string) ($event['after'] ?? ''), $fetch);
        }

        return null;
    }

    /**
     * A pull request's title and body as they are now, and each of its commits.
     *
     * @param callable(string): array<mixed> $fetch
     *
     * @return list<array{where: string, text: string, title?: bool}>
     */
    private static function pullRequest(string $repository, int $number, callable $fetch): array
    {
        $pull = $fetch("/repos/{$repository}/pulls/{$number}");
        $declared = $pull['commits'] ?? null;

        if (!\is_string($pull['title'] ?? null) || !\is_int($declared)) {
            throw new \RuntimeException("pull request #{$number} could not be read.");
        }

        if ($declared > self::LISTED_COMMITS) {
            throw new \RuntimeException("pull request #{$number} has {$declared} commits and the API lists " . self::LISTED_COMMITS . '; they cannot all be read.');
        }

        $texts = [
            ['where' => 'the pull request title', 'text' => $pull['title'], 'title' => true],
            ['where' => 'the pull request body', 'text' => (string) ($pull['body'] ?? '')],
        ];

        return [...$texts, ...self::pages("/repos/{$repository}/pulls/{$number}/commits", null, $declared, $fetch)];
    }

    /**
     * The commits a push added.
     *
     * @param callable(string): array<mixed> $fetch
     *
     * @return list<array{where: string, text: string}>
     */
    private static function push(string $repository, string $before, string $after, callable $fetch): array
    {
        if (preg_match('/^[0-9a-f]{40,64}$/', $after) !== 1 || trim($after, '0') === '') {
            throw new \RuntimeException('the push names no commit.');
        }

        // A branch that did not exist has nothing to be compared with: its tip is what arrived.
        if (preg_match('/^[0-9a-f]{40,64}$/', $before) !== 1 || trim($before, '0') === '') {
            return [self::commit($fetch("/repos/{$repository}/commits/{$after}"))];
        }

        return self::pages("/repos/{$repository}/compare/{$before}...{$after}", 'commits', null, $fetch);
    }

    /**
     * Reads a listing of commits page by page, and refuses to return fewer than were announced.
     *
     * @param string|null                    $key      where the commits sit in each answer (null: the answer is the list)
     * @param int|null                       $expected how many there are (null: the first answer says, as `total_commits`)
     * @param callable(string): array<mixed> $fetch
     *
     * @return list<array{where: string, text: string}>
     */
    private static function pages(string $path, ?string $key, ?int $expected, callable $fetch): array
    {
        $commits = [];

        for ($page = 1; $expected === null || \count($commits) < $expected; ++$page) {
            $answer = $fetch("{$path}?per_page=" . self::PAGE . "&page={$page}");

            if ($expected === null) {
                $expected = $answer['total_commits'] ?? null;
                if (!\is_int($expected)) {
                    throw new \RuntimeException('the push could not be compared with what was there before.');
                }
            }

            $listed = $key === null ? $answer : ($answer[$key] ?? null);
            if (!\is_array($listed) || $listed === []) {
                break;
            }

            foreach ($listed as $commit) {
                $commits[] = self::commit($commit);
            }
        }

        if (\count($commits) < $expected) {
            throw new \RuntimeException("{$expected} commits were announced and only " . \count($commits) . ' could be read.');
        }

        return $commits;
    }

    /**
     * One commit, as a text the gate can judge.
     *
     * @return array{where: string, text: string}
     */
    private static function commit(mixed $commit): array
    {
        $sha = \is_array($commit) ? ($commit['sha'] ?? null) : null;
        $message = \is_array($commit) ? ($commit['commit']['message'] ?? null) : null;

        if (!\is_string($sha) || !\is_string($message)) {
            throw new \RuntimeException('a commit came back without its message.');
        }

        return ['where' => 'commit ' . substr($sha, 0, 9), 'text' => $message];
    }

    /**
     * Splits "owner/repo#12" into its repository and number.
     *
     * @return array{string, int}
     */
    private static function named(string $reference): array
    {
        if (preg_match('~^([\w.-]+/[\w.-]+)#(\d+)$~', $reference, $m) !== 1) {
            throw new \RuntimeException('--pr takes owner/repo#number.');
        }

        return [$m[1], (int) $m[2]];
    }

    /**
     * The addresses a line names as co-authors; a trailer with no address counts as one unnamed.
     *
     * @return list<string>
     */
    private static function coauthors(string $line): array
    {
        if (preg_match_all('/co-authored-by\s*:(.*?)(?=co-authored-by\s*:|$)/i', $line, $trailers) < 1) {
            return [];
        }

        return array_map(
            static fn (string $named): string => preg_match('/<\s*([^<>\s]+)\s*>/', $named, $m) === 1 ? $m[1] : '',
            $trailers[1],
        );
    }

    /**
     * Whether a line is a generator's signature: it opens with the words, or links what generated it.
     */
    private static function signsAGenerator(string $line): bool
    {
        $opens = preg_match('/^(?:<[^>]*>|[^A-Za-z0-9<])*generated[\s-]+(?:with|by)\b/i', $line) === 1;
        $links = preg_match_all('~generated[\s-]+(?:with|by)\s+\[[^\]]*\]\(\s*(?:https?://)?([^)\s]*)~i', $line, $linked);

        if ($links > 0) {
            foreach ($linked[1] as $target) {
                if (!self::isAdmittedGenerator($target)) {
                    return true;
                }
            }

            return false;
        }

        return $opens;
    }

    /**
     * Whether a link target belongs to a generator the house admits.
     */
    private static function isAdmittedGenerator(string $target): bool
    {
        $target = strtolower(preg_replace('~^www\.~i', '', $target) ?? $target);

        foreach (self::ADMITTED_GENERATORS as $admitted) {
            if ($target === $admitted || str_starts_with($target, $admitted . '/') || str_starts_with($target, $admitted . '#')) {
                return true;
            }
        }

        return false;
    }

    /**
     * Whether a line points at a work session: a "…-Session:" trailer, or a link to a session page.
     */
    private static function refersToASession(string $line): bool
    {
        return preg_match('/^\s*(?:[A-Za-z0-9_]+-)+session(?:-(?:id|url|link))?\s*:/i', $line) === 1
            || preg_match('~https?://[^\s<>()\[\]"\'`]*/session[_-][A-Za-z0-9][A-Za-z0-9_-]{7,}~i', $line) === 1;
    }

    /**
     * A title without its conventional prefix, so "fix: generated by …" is read as the line it becomes.
     */
    private static function withoutPrefix(string $title): string
    {
        return preg_replace('/^\s*[a-z]+(?:\([^)]*\))?!?:\s*/i', '', $title) ?? $title;
    }

    /**
     * Says what was read, in the words of the summary line.
     *
     * @param list<array{where: string, text: string, title?: bool}> $texts
     */
    private static function tally(array $texts): string
    {
        $commits = \count(array_filter($texts, static fn (array $t): bool => str_starts_with($t['where'], 'commit ')));
        $others = \count($texts) - $commits;
        $parts = [];

        if ($others === 2) {
            $parts[] = 'the title and the body';
        } elseif ($others === 1) {
            $parts[] = 'one text';
        }

        if ($commits > 0 || $others === 0) {
            $parts[] = $commits . ($commits === 1 ? ' commit' : ' commits');
        }

        return implode(' and ', $parts);
    }
}

// Run only as a script: a test that requires this file gets the class and nothing else.
if (\PHP_SAPI === 'cli' && isset($_SERVER['SCRIPT_FILENAME']) && realpath((string) $_SERVER['SCRIPT_FILENAME']) === __FILE__) {
    $environment = [];
    foreach (['GITHUB_EVENT_NAME', 'GITHUB_EVENT_PATH', 'GITHUB_REPOSITORY'] as $name) {
        $value = getenv($name);
        if (\is_string($value)) {
            $environment[$name] = $value;
        }
    }

    $api = rtrim((string) (getenv('GITHUB_API_URL') ?: 'https://api.github.com'), '/');
    $token = (string) (getenv('GITHUB_TOKEN') ?: getenv('GH_TOKEN') ?: '');

    $fetch = static function (string $path) use ($api, $token): array {
        $headers = ['Accept: application/vnd.github+json', 'X-GitHub-Api-Version: 2022-11-28', 'User-Agent: milpa-message-gate'];
        if ($token !== '') {
            $headers[] = 'Authorization: Bearer ' . $token;
        }

        $status = 0;
        for ($attempt = 1; $attempt <= 3; ++$attempt) {
            $context = stream_context_create(['http' => ['method' => 'GET', 'header' => $headers, 'timeout' => 20, 'ignore_errors' => true]]);
            $body = @file_get_contents($api . $path, false, $context);
            $answered = \function_exists('http_get_last_response_headers') ? (http_get_last_response_headers() ?? []) : ($http_response_header ?? []);
            $status = preg_match('~^HTTP/\S+\s+(\d{3})~', (string) ($answered[0] ?? ''), $m) === 1 ? (int) $m[1] : 0;

            if ($body !== false && $status === 200) {
                $decoded = json_decode($body, true);
                if (\is_array($decoded)) {
                    return $decoded;
                }
            }

            // A refusal is an answer; only silence and a failing server are worth asking again.
            if ($status !== 0 && $status < 500 && $status !== 429) {
                break;
            }

            if ($attempt < 3) {
                sleep($attempt);
            }
        }

        throw new \RuntimeException('the API answered ' . ($status === 0 ? 'nothing' : (string) $status) . ' to ' . strtok($path, '?') . '.');
    };

    $stdin = \in_array('--stdin', $argv, true) ? (string) stream_get_contents(\STDIN) : '';

    exit(MessageGate::run($argv, $environment, $fetch, static function (string $line): void {
        echo $line, \PHP_EOL;
    }, $stdin));
}
